version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - news_board/.env
    volumes:
      - .:/news_board
    depends_on:
      - db
    restart: always
  db:
    image: postgres:13
    env_file:
      - news_board/.env
    restart: always